### ISSUE TITLE
Show List command

### ISSUE THREAD

**Issue by Zuwel** [Zuwel/FireworkShowPlus#3] opened 2020-09-12 01:18 UTC
Sends a list of available shows to the player. Should be tabulated into pages. Possibly include the number of frames and the total length of the show in seconds.

**Comment by Jackietkfrost** [comment] 2020-09-12 11:38
Duplicate of #5

**Closed as completed by Jackietkfrost** 2020-09-12 11:38 UTC
Labels: enhancement

**Comment by Jackietkfrost** [comment] 2020-09-12 11:42
List Added. Will eventually have hoverable events and whatnot :)
